### ISSUE TITLE
Suggestion:  Add a log level :security for rapid detection of potential threat scenarios

### ISSUE THREAD

**Issue by joshk6** [rocketjob/semantic_logger#127]
This would come in handy in my rails code to quickly identify  any spike in attempts to gain access to resources to which the user is not authorized to access. I have code in my project to prevent it, but it would be handy to have a monitor which alerts on unusually high levels of :security log level entries.

**Comment by joshk6** [comment]
This would come in handy in my rails code to quickly identify  access attempts to gain unauthorized access to resources to which the user is not authorized to access.  I have code in my project to prevent it, but it would be handy to have a monitor which alerts on unusually high levels of :security log level entries.

**Comment by reidmorrison** [comment]
Very interesting idea. Have not seen any other logging framework that took security alerts this seriously.

We use a centralized logging system that we forward JSON logs to called Splunk, and have a custom metric name that we assign to all security related logging events so that Splunk can log and generate the necessary security alerts.
https://rocketjob.github.io/semantic_logger/metrics.html

**Comment by rene-s** [comment]
There ususally is no "security" log level, because log levels are standardized (see https://tools.ietf.org/html/rfc5424#section-6.2.1) and log level "alert" (log level 1 of 0...7) already means "action must be taken immediately". This also applies to security alerts in my opinion.

**Comment by reidmorrison** [comment]
We use metrics for all of our security alerts and have found it to be very useful.
