### ISSUE TITLE
Logger returns .level as a Fixnum, not Symbol

### ISSUE THREAD

**Issue by ojab** [rocketjob/semantic_logger#28]
SemanticLogger returns .level as a Symbol, while Logger returns it as a Fixnum:
```ruby
2.3.0 :003 > Logger.new(STDOUT).level
 => 0
2.3.0 :004 > SemanticLogger['MyClass'].level
 => :info
```
which makes SemanticLogger not so drop-in replacement, see https://github.com/typhoeus/ethon/pull/127

**Comment by reidmorrison** [comment]
Looking at the reference supplied it is not recommended in Ruby to ever use the numeric value for a constant directly. In the reference a check is made for zero. This incorrectly assumes that the constant value will never change between releases.
With logging the correct mechanism to use is '.debug?' not 'level.zero?'.

By design Semantic Logger does not return a number for the log level since the numbers in Logger are a subset of the range of log levels actually supported by Semantic Logger.
For example ':trace' log level does not exist in Logger, only in Semantic Logger.

By drop in replacement we  mean it can replace existing code that works properly with Logger. 

I.e. This feature is by design and is not a bug

**Comment by ojab** [comment]
Yeah, using `.debug?` is the better way, but `level.zero?` or `level == Logger::WARN` also works fine with Logger.
AFAICS there is direct mapping between Logger & SemanticLogger levels :debug, :info, :warn, :error & :fatal, so there is a reasonable expectation that 'Drop-in Replacement' will return `.level` in the same format that Logger does.

So I'm absolutely not defending checks that use `.level` comparison, but without fixing this issue `Drop-in Replacement` declaration is inaccurate and should be more like `Drop-in Replacement (with caveats)`.
