### ISSUE TITLE
Discuss: should the payload be merged when `to_h`?

### ISSUE THREAD

**Issue by lerencao** [rocketjob/semantic_logger#35]
As the source code shows, when payload is a hash, it will be merged into the hash output.
As I can see, there is a potential problem: When payload contains an duplicate field(say: `message` or `line`), it will override the log message, or the file line number. Users need to go to the source code to find out the problem.

**Comment by reidmorrison** [comment]
Want to submit a documentation PR to list the `reserved` keywords?
The documentation is on the `gh-pages` branch and uses the same markup as github.

We could also recommend that to avoid conflicts when using the payload is to store its data in a child element of the Hash.
Additionally the `#to_h` could be changed to apply the payload last so that the payload takes priority over the built-in reserved keywords.

**Comment by lerencao** [comment]
Making it clear in doc is good to go. 
But why not just put the payload in a `reserved` filed like `payload`.
It makes the intention more explicit.

**Comment by reidmorrison** [comment]
We cannot break the current behavior for everyone, however using a custom formatter you can definitely move the payload into a a special field like `payload`

**Comment by reidmorrison** [comment]
After much deliberation I agree with you that payload belongs in its own tag called `payload`. Unfortunately this may break a handful of installations, but will be worth the migration pain.
Will have a fix in the next major release, which will also require Ruby 2.0 at a minimum.
`with_payload` will also be removed and replaced with `SemanticLogger#named_tagged`. The named tags will no longer be merged into payload and will be a separate tag called `named_tags`

**Comment by lerencao** [comment]
That's great. Looking forward to the new major release. Closing it now. ~~
