### ISSUE TITLE
Make tags accessible from other threads ?

### ISSUE THREAD

**Issue by lerencao** [rocketjob/semantic_logger#46]
Hi, Is there any plan to make tags accessible from other threads?

The case that tag information is related with current thread(not with a logger instance) can hardly make sense.

If you guys have the same thought, I can make a PR to solve this issue.

**Comment by reidmorrison** [comment]
Tags are on a per thread basis. The methods are available via instance methods on the logger instance for convenience only.

When using raw threads directly it is necessary to manually copy any tags from the current thread to the new one if they are needed by the new thread.

Instead of using raw threads, look at [Parallel Minion](http://reidmorrison.github.io/parallel_minion/), it handles copying tags to the new thread and wraps the new thread with Semantic Logger logging calls.

**Comment by lerencao** [comment]
Yes, that's how I handle the tags in multi threads.
But In my opinion, this situation can be and should be avoided.
Tags, attached in every logs emitted by a logger, should be handled in the logger, not the thread.

**Comment by reidmorrison** [comment]
Tags are per thread by design, otherwise we would not be able to use Semantic Logger in a multi-threaded application. Every class has its own logger, so setting tags for each and every class would be a substantial coding effort and would pollute tags set by other threads using the same classes or instances of those classes.

**Comment by reidmorrison** [comment]
Works as designed. Look at [Parallel Minion](http://reidmorrison.github.io/parallel_minion/) to automatically copy tags across threads.
