### ISSUE TITLE
Breaks quiet_assets

### ISSUE THREAD

**Issue by pmackay** [rocketjob/semantic_logger#48]
I have added semantic_logger to a project that already had the [quiet_assets](https://github.com/evrone/quiet_assets) gem and now am getting lots of output like:

```
2017-01-17 08:52:35.401833 D [20492:puma 005] Rails --
2017-01-17 08:52:35.401917 D [20492:puma 005] Rails --
2017-01-17 08:52:35.402101 D [20492:puma 005] Rails -- Started -- { :method => "GET", :path => "/assets/ckeditor/init.self-2f3e80b764bc18c9362e6f3326e1f32d4a8bdceff67345a3453a93b111626ff3.js?body=1", :ip => "::1" }
```

Quiet assets is intended to suppress this. Is this a known conflict? Is there any way to configure semantic logger to also suppress this output or could it be made compatible with quiet assets?

**Comment by reidmorrison** [comment]
Looks like quiet assets is deprecated and there is now a Rails config option that does the same thing.

Alternatively remove the quiet_assets gem and add a filter to the Rails rack logger that removes the messages by using the same logic that the `quiet_assets` gem uses.

Filter docs https://rocketjob.github.io/semantic_logger/filtering.html

The code below would be a starting point, and by looking at https://github.com/evrone/quiet_assets/blob/master/lib/quiet_assets.rb

~~~ruby
Rails.logger.filter = Proc.new do |log| 
  if log.message.blank? || 
    (log.payload && log.payload.is_a?(Hash) && (log.payload[:path].include?('/assets')))
    false
  end
   true
  end
end
~~~

**Comment by reidmorrison** [comment]
This is now fixed in the [rails_semantic_logger](https://github.com/rocketjob/rails_semantic_logger) gem with the following commit:
https://github.com/rocketjob/rails_semantic_logger/commit/d3b2906a15692ffd5856bfa5c182c24212293339

To quiet asset logging remove the `quiet_assets` gem and add the following to `config/development.rb`:

~~~ruby
# Silence asset logging
config.rails_semantic_logger.quiet_assets = true
~~~

The changes are currently in the master branch of rails_semantic_logger.
