### ISSUE TITLE
Better elasticsearch support

### ISSUE THREAD

**Issue by xrl** [rocketjob/semantic_logger#64]
Would this project be open to accepting a patch for more efficient bulk indexing in Elasticsearch? Right now I can tell it's doing a POST for each log message -- this could be handled much more efficiently using the bulk api: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html .

If I wrote this would it be suitable for inclusion? My plan right now is to drag in the `elasticsearch-ruby` gem to handle bulking and flushing.

**Comment by reidmorrison** [comment]
Yes, we welcome community enhancements. In fact most appenders arr community contributed.

Would be great to have a bulk loading capability. We use splunk and had to revert to writing to a JSON log file since the http load technique was too slow.

Just use the soft dependency on the additional gem. See other spenders for an example.

**Comment by xrl** [comment]
Cool! I'm working on it now.

**Comment by prikha** [comment]
Nice! Looking forward to see in merged. Mention if help needed

**Comment by xrl** [comment]
I'm burning it in right now. I had some issues with not reading the manual, so my puma-powered app was misbehaving and it took me a while to figure it out. Otherwise pretty straight-forward code.
