### ISSUE TITLE
In Sidekiq, logs are batched before sending for hours

### ISSUE THREAD

**Issue by ericgross** [rocketjob/semantic_logger#80]
How should I configure SemanticLogger/Sidekiq to flush the logs on a regular basis?

**Comment by reidmorrison** [comment]
You should not have to flush the logs since most appenders write their data immediately to the log file in a separate thread.
When the process exits it calls `SemanticLogger.flush` so that the process waits for all inflight data to be written prior to exiting.

If you are using process forking it results in no data being logged unless the necessary forking callbacks have been added:
https://rocketjob.github.io/semantic_logger/forking.html

The above callbacks are necessary to re-open file handles that are lost when processes are forked.

**Comment by Silex** [comment]
@reidmorrison: how can we _prevent_ SemanticLogger from handling Sidekiq's logs? Given having useful Sidekiq logs is a bit of a pain (see #51).

I know it gets replaced here: https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/engine.rb#L213

But it's not that easy to replace it with it's original value :-/

Maybe in some initializer before SemanticLogger is loaded, store the old value and restore it after SemanticLogger is initialized? Not sure if feasible tho.

**Comment by reidmorrison** [comment]
In an after initialize you can set the `Sidekiq.logger=` to the regular ruby logger if you want.

Alternatively, build a wrapper for the Sidekiq logger that captures the additional data and then forwards it to Semantic Logger using its api. We could then make this wrapper a built-in feature in Rails Semantic Logger.

**Comment by reidmorrison** [comment]
Logs that stop writing are usually due to a process forking issue. If anyone has example code for the various forking platforms, please let us know so that we can add it to the documentation.

**Comment by VipulSarin** [comment]
Resque prevents at_exit hooks from running by default. Due to this, semantic logger fails to flush logs. Here is the relevant documentation in Resque - https://github.com/resque/resque/blob/529eb243575b428da7afbb55ff2e8c4c68c30aee/docs/HOOKS.md

To run correctly, Semantic Logger requires that jobs sets `run_at_exit_hook = 1`
