### ISSUE TITLE
Any interest in supporting arbitrary hash values for messages

### ISSUE THREAD

**Issue by shulmang** [rocketjob/semantic_logger#81]
I’m curious if there is any enthusiasm for supporting payloadesq data in messages.  The payload change seems like a good idea to avoid collisions.  I’m wondering, though, if not accepting arbitrary keys in message hashes is in line with common ruby/rails logging?  For example this seems to break GrapeLogger by default.  As such would supporting something like the following be appealing?

          it 'logs arbitrary keyword args to payload' do
            random_key = rand(36**8).to_s(36)
            random_value = rand(36**8).to_s(36)
            random_payload = {random_key => random_value}
            logger.send(level, random_payload)

            assert_equal random_payload, log.payload
          end

**Comment by reidmorrison** [comment]
If I understand correctly, you want to it to automatically assume that any data passed in as an argument that is not recognized as an internal key should be logged as the payload?

~~~ruby
logger.info "hello", duration: 3, username: 'Jack'
~~~

Is this what you had in mind?

**Comment by shulmang** [comment]
Yes.  The default rails logger supports arbitrary objects as messages, including hashes and just calls to_s on them.  There are community gems in the wild which take advantage of this contract and pass hashes as messages.   The payload change breaks this contract by raising in assign if non-semantic-logger keys are passed in messages.  So, the above suggestion could be considered defensive to accommodate the default rails logger behavior.  Although, perhaps it does somewhat defeat the intention of the payload change to avoid collisions.  An alternative might be to invert the strategy and move semantic logger specific fields into their own parameter.  So the signature for send might be something like (message=nil, instrumentation=nil, exception=nil, &block)

**Comment by reidmorrison** [comment]
I searched the ruby grape code for logger usages and did not find anything built-in that would log anything other than a string.

Instead of using their logger helper, it would be better to do something like:

~~~ruby
class API < Grape::API
  include SemanticLogger::Loggable
  get '/statuses' do
    logger.warning "#{current_user} has statused"
  end
end
~~~

Or better still make the logger standard with a one line initializer:
~~~ruby
Grape::API.include(SemanticLogger::Loggable)
~~~
And then every api instance can log:
~~~ruby
class API < Grape::API
  get '/statuses' do
    logger.warning "#{current_user} has statused"
  end
end
~~~

If the above one line initializer works in Ruby grape, maybe we should include it as standard in Rails Semantic Logger so that it is always added for anyone using Ruby Grape.

**Comment by shulmang** [comment]
👍
